object Versions {
    const val coreLibrary = "1.1.5"
    const val gradle = "7.0.0"
    const val kotlinGradlePlugin = "1.5.21"
    const val navigation = "2.3.5"
    const val retrofit = "2.9.0"
    const val hilt = "2.38.1"
    const val okhttp3 = "4.9.1"
    const val gson = "2.8.6"
    const val moshi = "1.12.0"
    const val kotlinStdlib = "1.5.21"
    const val coreKtx = "1.6.0"
    const val appcompat = "1.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.0"
    const val swipeRefreshLayout = "1.1.0"
    const val junit = "4.13.2"
    const val testJunit = "1.1.3"
    const val testEspressoCore = "3.4.0"
    const val kakaoUser = "2.6.0"
    const val lifecycle = "2.4.0-alpha02"
    const val glide = "4.12.0"
    const val cardStackView = "2.3.4"
    const val lottie = "3.0.7"
}